CREATE TABLE "USER" (
  ID SERIAL,
  NAME VARCHAR(100), 
  EMAIL VARCHAR(100), 
  PASSWORD VARCHAR(100)
);

CREATE TABLE "SIMULATION" (
  ID SERIAL,
  DESCRIPTION VARCHAR(200),
  PLOTS INT,
  VALOR DECIMAL
);

CREATE TABLE "CONTACT" (
  ID SERIAL,
  NAME VARCHAR(100),
  EMAIL VARCHAR(200),
  MESSAGE VARCHAR(200)
);