CREATE TABLE "USER" (
  ID SERIAL,
  NAME VARCHAR(100), 
  EMAIL VARCHAR(100), 
  PASSWORD VARCHAR(100),
  ROLE INT
);

CREATE TABLE "SIMULATION" (
  ID SERIAL,
  DESCRIPTION VARCHAR(200),
  PLOTS INT,
  AMOUNT DECIMAL,
  EMAIL VARCHAR(100),
	USER_ID INT,
  CREATED_AT TIMESTAMP,
  APPROVED_AT TIMESTAMP
);

CREATE TABLE "CONTACT" (
  ID SERIAL,
  NAME VARCHAR(100),
  EMAIL VARCHAR(200),
  MESSAGE VARCHAR(200)
);

INSERT INTO "USER" (NAME, EMAIL, PASSWORD, ROLE) VALUES ('approver', 'approver@fakebank.lab', '123', 1);